import { logActivity } from '../utils/activityTracker'
import { createContext, useContext, useState, useEffect, useCallback } from 'react'
import { toast } from './ToastContext'

const BookmarkContext = createContext()

const KEY_BOOKMARKS = 'nsn-bookmarks'
const KEY_NOTES = 'nsn-notes'
const KEY_RECENT = 'nsn-recent'

function readStorage(key, fallback) {
  try {
    const raw = localStorage.getItem(key)
    return raw ? JSON.parse(raw) : fallback
  } catch {
    return fallback
  }
}

export function BookmarkProvider({ children }) {
  const [bookmarks, setBookmarks] = useState(() => readStorage(KEY_BOOKMARKS, []))
  const [notes, setNotes] = useState(() => readStorage(KEY_NOTES, {}))
  const [recentlyViewed, setRecentlyViewed] = useState(() => readStorage(KEY_RECENT, []))

  useEffect(() => {
    localStorage.setItem(KEY_BOOKMARKS, JSON.stringify(bookmarks))
  }, [bookmarks])

  useEffect(() => {
    localStorage.setItem(KEY_NOTES, JSON.stringify(notes))
  }, [notes])

  useEffect(() => {
    localStorage.setItem(KEY_RECENT, JSON.stringify(recentlyViewed))
  }, [recentlyViewed])

  const isBookmarked = useCallback(
    (id) => bookmarks.includes(id),
    [bookmarks]
  )

  const toggleBookmark = useCallback((id) => {
  setBookmarks((prev) => {
    const adding = !prev.includes(id)
    const next = adding ? [...prev, id] : prev.filter((b) => b !== id)

    // Toast feedback
    toast(adding ? 'Bookmark added ✓' : 'Bookmark removed', adding ? 'success' : 'info')

    // Log activity
    logActivity(adding ? 'bookmark-add' : 'bookmark-remove', { id })

    // Celebrate on unlock thresholds
    if (adding) {
      const milestones = [1, 5, 10, 15, 20]
      if (milestones.includes(next.length)) {
        import('../utils/celebrate').then((m) => m.celebrate())
      }
    }

    return next
  })
}, [])

  const removeBookmark = useCallback((id) => {
    setBookmarks((prev) => prev.filter((b) => b !== id))
  }, [])

  const clearBookmarks = useCallback(() => {
    setBookmarks([])
    setNotes({})
  }, [])

  const setNote = useCallback((id, text) => {
    setNotes((prev) => ({ ...prev, [id]: text }))
  }, [])

  const getNote = useCallback((id) => notes[id] || '', [notes])

  const addRecent = useCallback((id) => {
    setRecentlyViewed((prev) => {
      const filtered = prev.filter((r) => r !== id)
      return [id, ...filtered].slice(0, 6)
    })
  }, [])

  // Export as .txt
  const exportBookmarks = useCallback((careers) => {
    const list = careers.filter((c) => bookmarks.includes(c.id))
    const lines = []
    lines.push('═══════════════════════════════════════════════')
    lines.push('  NextStep Navigator — My Bookmarked Careers')
    lines.push(`  Exported: ${new Date().toLocaleString()}`)
    lines.push(`  Total: ${list.length}`)
    lines.push('═══════════════════════════════════════════════')
    lines.push('')

    list.forEach((c, i) => {
      lines.push(`${i + 1}. ${c.title} (${c.industry})`)
      lines.push(`   Salary: $${c.salaryMin.toLocaleString('en-US')} – $${c.salaryMax.toLocaleString('en-US')} p.a.`)
      lines.push(`   Skills: ${c.skills.join(', ')}`)
      lines.push(`   Education: ${c.educationPath}`)
      if (notes[c.id]) {
        lines.push(`   📝 Note: ${notes[c.id]}`)
      }
      lines.push('')
    })

    lines.push('Generated by NextStep Navigator — Your Guide to the Future')

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `nextstep-bookmarks-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast('Bookmarks exported', 'success')
  }, [bookmarks, notes])

  const shareBookmarks = useCallback(async (careers) => {
    const list = careers.filter((c) => bookmarks.includes(c.id))
    const text = `My career shortlist on NextStep Navigator:\n\n${list
      .map((c, i) => `${i + 1}. ${c.title} (${c.industry})`)
      .join('\n')}\n\nExplore more at NextStep Navigator.`
    const shareData = {
      title: 'My Career Shortlist — NextStep Navigator',
      text,
      url: window.location.origin,
    }
    try {
      if (navigator.share) {
        await navigator.share(shareData)
      } else {
        await navigator.clipboard.writeText(text)
        alert('Copied to clipboard! Paste it anywhere to share.')
      }
    } catch (err) {
      // user cancelled — ignore
    }
  }, [bookmarks])

  return (
    <BookmarkContext.Provider
      value={{
        bookmarks,
        notes,
        recentlyViewed,
        isBookmarked,
        toggleBookmark,
        removeBookmark,
        clearBookmarks,
        setNote,
        getNote,
        addRecent,
        exportBookmarks,
        shareBookmarks,
      }}
    >
      {children}
    </BookmarkContext.Provider>
  )
}

export function useBookmarks() {
  const ctx = useContext(BookmarkContext)
  if (!ctx) throw new Error('useBookmarks must be used inside <BookmarkProvider>')
  return ctx
}